import Link from "next/link";
import { notFound } from "next/navigation";
import { AiBadge, PriorityLabel, TypeBadge } from "@/components/common/badges";
import { CodeReview } from "@/components/automation/code-review";
import { RunAutomationButton } from "@/components/automation/run-automation-button";
import { Badge } from "@/components/ui/badge";
import { getServiceContext } from "@/lib/server-context";
import { formatDateTime } from "@/lib/utils";

export const metadata = { title: "Automation Draft" };

export default async function AutomationTestPage({ params }: PageProps<"/automation/tests/[id]">) {
  const { id } = await params;
  const ctx = await getServiceContext();
  const automation = await ctx.repo.getAutomationTest(id);
  if (!automation) notFound();
  const [testCase, project] = await Promise.all([ctx.repo.getTestCase(automation.testCaseId), ctx.repo.getProject(automation.projectId)]);
  if (!testCase || !project) notFound();
  const fromAi = automation.generatedBy && automation.generatedBy !== "heuristic" && automation.generatedBy !== "demo-seed";

  return (
    <>
      <div className="border-b px-6 py-4">
        <div className="mb-1 flex items-center gap-2 text-xs text-muted-foreground">
          <Link href="/automation" className="hover:underline">
            Automation
          </Link>
          <span>/</span>
          <Link href={`/projects/${project.key}/automation`} className="hover:underline">
            {project.key}
          </Link>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <h1 className="text-lg font-semibold tracking-tight">Automation Draft · {testCase.caseKey}</h1>
          {automation.status === "approved" ? (
            <Badge variant="passed">Approved</Badge>
          ) : automation.status === "rejected" ? (
            <Badge variant="skipped">Rejected</Badge>
          ) : (
            <Badge variant="warning">Draft · needs review</Badge>
          )}
          {fromAi ? <AiBadge /> : <Badge variant="outline">Rule-based draft</Badge>}
          <div className="ml-auto">
            <RunAutomationButton
              projectId={project.id}
              testCaseIds={[testCase.id]}
              automatedCount={automation.status === "approved" ? 1 : 0}
              label="Run"
            />
          </div>
        </div>
        <p className="mt-1 text-xs text-muted-foreground">
          Generated by {automation.generatedBy ?? "—"} · updated {formatDateTime(automation.updatedAt)}
          {automation.approvedAt ? ` · approved ${formatDateTime(automation.approvedAt)}` : ""}
          {automation.reviewNote ? ` · ${automation.reviewNote}` : ""}
        </p>
      </div>
      <div className="grid gap-6 p-6 xl:grid-cols-[22rem_minmax(0,1fr)]">
        <aside className="space-y-4 text-[13px]">
          <div>
            <Link href={`/cases/${testCase.id}`} className="font-medium hover:underline">
              {testCase.title}
            </Link>
            <div className="mt-1 flex flex-wrap gap-1.5">
              <TypeBadge type={testCase.type} />
              <PriorityLabel priority={testCase.priority} />
            </div>
          </div>
          <section>
            <h3 className="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Preconditions</h3>
            <p>{testCase.preconditions || "None"}</p>
          </section>
          <section>
            <h3 className="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Steps</h3>
            <ol className="list-decimal space-y-1 pl-5">
              {testCase.steps.map((step, index) => (
                <li key={index}>{step}</li>
              ))}
            </ol>
          </section>
          <section>
            <h3 className="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Expected Result</h3>
            <p>{testCase.expectedResult}</p>
          </section>
          <section>
            <h3 className="mb-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">Target</h3>
            <p className="break-all text-xs">{project.appUrl ?? "No Application URL set"}</p>
          </section>
        </aside>
        <CodeReview
          key={automation.updatedAt}
          automationTestId={automation.id}
          testCaseId={testCase.id}
          initialCode={automation.code}
          status={automation.status}
          filePath={automation.filePath}
        />
      </div>
    </>
  );
}
